(function() {var implementors = {};
implementors['rustc_serialize'] = ["<a class='stability Stable' title='Stable'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;<a class='struct' href='http://doc.rust-lang.org/nightly/core/fmt/struct.Error.html' title='core::fmt::Error'>Error</a>&gt; for <a class='enum' href='rustc_serialize/json/enum.EncoderError.html' title='rustc_serialize::json::EncoderError'>EncoderError</a>",];implementors['geojson'] = ["<a class='stability Stable' title='Stable'></a>impl&lt;'a&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;&amp;'a <a class='enum' href='geojson/enum.Crs.html' title='geojson::Crs'>Crs</a>&gt; for <a class='type' href='rustc_serialize/json/type.Object.html' title='rustc_serialize::json::Object'>Object</a>","<a class='stability Stable' title='Stable'></a>impl&lt;'a&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;&amp;'a <a class='enum' href='geojson/enum.GeoJson.html' title='geojson::GeoJson'>GeoJson</a>&gt; for <a class='type' href='rustc_serialize/json/type.Object.html' title='rustc_serialize::json::Object'>Object</a>","<a class='stability Stable' title='Stable'></a>impl&lt;'a&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;&amp;'a <a class='struct' href='geojson/struct.Geometry.html' title='geojson::Geometry'>Geometry</a>&gt; for <a class='type' href='rustc_serialize/json/type.Object.html' title='rustc_serialize::json::Object'>Object</a>","<a class='stability Stable' title='Stable'></a>impl&lt;'a&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;&amp;'a <a class='struct' href='geojson/struct.Feature.html' title='geojson::Feature'>Feature</a>&gt; for <a class='type' href='rustc_serialize/json/type.Object.html' title='rustc_serialize::json::Object'>Object</a>","<a class='stability Stable' title='Stable'></a>impl&lt;'a&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;&amp;'a <a class='struct' href='geojson/struct.FeatureCollection.html' title='geojson::FeatureCollection'>FeatureCollection</a>&gt; for <a class='type' href='rustc_serialize/json/type.Object.html' title='rustc_serialize::json::Object'>Object</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
